CREATE TABLE [dbo].[Raitings](
	[RaitingID] [int] NOT NULL,
	[RaitingValue] [int] NOT NULL,
 CONSTRAINT [PK_Raitings] PRIMARY KEY CLUSTERED 
(
	[RaitingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]